title: XML for Digital Scholarly Editing
description: A full-day workshop teaching students basic technologies for Digital Scholarly Editing (TEI-XML, HTML, CSS) from scratch.
theme: just-the-docs

url: https://WoutDLN.github.io/xml4dse-workshop

aux_links:
  Template Repository: https://github.com/WoutDLN/xml4dse-workshop
