title: XML for Digital Scholarly Editions
description: A full-day workshop teaching students basic technologies for Digital Scholarly Editing (TEI-XML, HTML, CSS) from scratch.
theme: just-the-docs

url: https://WoutDLN.github.io/xml4dse-workshop

aux_links:
  GitHub Repository: https://github.com/WoutDLN/xml4dse-workshop

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# I tried to copy the GitHub Pages default settings as much as possible
# See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
callouts:
  highlight:
    color: purple
  tip:
    title: 💡 Tip
    color: green
  note:
    title: ⓘ Note
    color: blue
  disclaimer:
    title: ⚠ Disclaimer
    color: blue
  warning:
    title: ⚠ Warning
    color: yellow
  important:
    title: ⚠ Important
    color: yellow
  caution:
    title: 🛑 Caution
    color: red
  danger:
    title: 🛑 Danger
    color: red

